
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Base64;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel; 
import java.sql.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author acv
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private String currentSemester;
    private String author;
    private String project;

    public MainFrame() {
        initComponents();
        checkData();
        rebuildSemesterComboBoxes();
        rebuildComboBoxes();
    }
    
    
    public void rebuildSemesterComboBoxes() {
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
        if (semesters.size() > 0) {
            currentSemesterLabel.setText(semesters.get(0));
            currentSemester = semesters.get(0);
        } else {
            currentSemesterLabel.setText("None, add a semester.");
            currentSemester = "None";
        }
        ArrayList<StudentEntry> se = StudentQueries.getAllStudents();
        ArrayList<String> students = new ArrayList<String>();
        for (StudentEntry s : se) {
            students.add(s.getLastName()+", "+s.getFirstName() + " " + s.getStudentID());
        }
        if (students.size() > 0) {
            currentCustomerTextField.setText(students.get(0));
        } else {
            currentCustomerTextField.setText("None, add a student.");
        }
    }
    public void rebuildComboBoxes() {
        // student combo box
        if (currentCustomerTextField.equals("None, add a student.")) {
            ArrayList<StudentEntry> se = StudentQueries.getAllStudents();
            currentCustomerTextField.setText(se.getLastName() + ", "+ se.getFirstName() + " " + se.getStudentID());
        }
        ArrayList<StudentEntry> se = StudentQueries.getAllStudents();
        ArrayList<String> students = new ArrayList<String>();
        for (StudentEntry s : se) {
            students.add(s.getLastName()+", "+s.getFirstName() + " " + s.getStudentID());
        }
        currentCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        deleteProductComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        
        //course combo box
        ArrayList<String> courses = new ArrayList<String>();
        if (SemesterQueries.getSemesterList().size() > 0) {
            courses = CourseQueries.getAllCourseCodes(currentSemesterComboBox.getSelectedItem().toString());
            
        }
        ArrayList<ScheduleEntry> schedule = new ArrayList<ScheduleEntry>();
        ArrayList<String> studentSchedule = new ArrayList<String>();
        if (SemesterQueries.getSemesterList().size() > 0 && students.size() > 0) {
            schedule = ScheduleQueries.getScheduleByStudent(currentSemesterLabel.getText(), currentCustomerTextField.getText().split(" ", 3)[2]);
            for (ScheduleEntry s : schedule) {
                studentSchedule.add(s.getCourseCode());
            }
        }

        deleteItemComboBox.setModel(new javax.swing.DefaultComboBoxModel(studentSchedule.toArray()));
        listSelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        addProductComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        deleteCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        addProductNameLabel = new javax.swing.JLabel();
        addProductNameTextField = new javax.swing.JTextField();
        addProductIDLabel = new javax.swing.JLabel();
        addProductIDTextField = new javax.swing.JTextField();
        addCourseSeatsLabel = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        addCourseLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addProductStatusLabel = new javax.swing.JLabel();
        addPriceTextField = new javax.swing.JTextField();
        addTypeLabel = new javax.swing.JLabel();
        addTypeTextField = new javax.swing.JTextField();
        addWeightLabel = new javax.swing.JLabel();
        addWeightTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        addStudentStudentIDLabel = new javax.swing.JLabel();
        addFirstNameLabel = new javax.swing.JLabel();
        addLastNameLabel = new javax.swing.JLabel();
        addCustomerIDTextField = new javax.swing.JTextField();
        addFirstNameTextField = new javax.swing.JTextField();
        addLastNameTextField = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        addCustomerStatusLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        deleteProductLabel = new javax.swing.JLabel();
        deleteProductComboBox = new javax.swing.JComboBox<>();
        deleteProductButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        deleteProductTextArea = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        deleteCustomerLabel = new javax.swing.JLabel();
        deleteCustomerComboBox = new javax.swing.JComboBox<>();
        dropCourseButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        deleteCustomerTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        displayProductsButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayProductsTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        addProductLabel = new javax.swing.JLabel();
        addProductComboBox = new javax.swing.JComboBox<>();
        addCustomerProductButton = new javax.swing.JButton();
        addCustomerProductStatusLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayCartTable = new javax.swing.JTable();
        displayScheduleButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        deleteItemLabel = new javax.swing.JLabel();
        deleteItemComboBox = new javax.swing.JComboBox<>();
        deleteItemButton = new javax.swing.JButton();
        currentCustomerLabel = new javax.swing.JLabel();
        currentCustomerTextField = new javax.swing.JLabel();
        currentCustomerComboBox = new javax.swing.JComboBox<>();
        changeCustomerButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventory Manager");

        addProductNameLabel.setText("Product Name:");

        addProductNameTextField.setColumns(20);

        addProductIDLabel.setText("Product ID:");

        addProductIDTextField.setColumns(50);

        addCourseSeatsLabel.setText("Price:");

        addProductButton.setText("Submit");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        addProductStatusLabel.setText("                                                   ");

        addProductIDTextField.setColumns(20);

        addTypeLabel.setText("Type:");

        addProductIDTextField.setColumns(20);

        addWeightLabel.setText("Weight:");

        addProductIDTextField.setColumns(20);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(addProductNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(addProductIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addProductIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(addCourseSeatsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(addPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(addProductButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(addTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCourseLabel)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addWeightLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addProductStatusLabel)))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProductNameLabel)
                    .addComponent(addProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProductIDLabel)
                    .addComponent(addProductIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCourseSeatsLabel)
                    .addComponent(addPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTypeLabel)
                    .addComponent(addTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addWeightLabel)
                    .addComponent(addWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCourseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addProductButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProductStatusLabel)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Product", jPanel4);

        addStudentStudentIDLabel.setText("Customer ID:");

        addFirstNameLabel.setText("First Name:");

        addLastNameLabel.setText("Last Name:");

        addCustomerIDTextField.setColumns(20);
        addCustomerIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerIDTextFieldActionPerformed(evt);
            }
        });

        addFirstNameTextField.setColumns(20);

        addLastNameTextField.setColumns(20);

        addCustomerButton.setText("Submit");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        addCustomerStatusLabel.setText("                                                                             ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(addStudentStudentIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCustomerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(addFirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(addLastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCustomerButton)
                            .addComponent(addLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addCustomerStatusLabel))
                .addContainerGap(528, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentStudentIDLabel)
                    .addComponent(addCustomerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFirstNameLabel)
                    .addComponent(addFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLastNameLabel)
                    .addComponent(addLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCustomerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCustomerStatusLabel)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Customer", jPanel5);

        deleteProductLabel.setText("Select Product:");

        deleteProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deleteProductButton.setText("Delete Product");
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });

        deleteProductTextArea.setColumns(20);
        deleteProductTextArea.setRows(5);
        jScrollPane6.setViewportView(deleteProductTextArea);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(deleteProductLabel)
                        .addGap(18, 18, 18)
                        .addComponent(deleteProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(deleteProductButton)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteProductLabel)
                    .addComponent(deleteProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProductButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Delete Product", jPanel12);

        deleteCustomerLabel.setText("Select Customer:");

        deleteCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dropCourseButton.setText("Delete Customer");
        dropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropCourseButtonActionPerformed(evt);
            }
        });

        deleteCustomerTextArea.setColumns(20);
        deleteCustomerTextArea.setRows(5);
        jScrollPane7.setViewportView(deleteCustomerTextArea);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(deleteCustomerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(dropCourseButton)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomerLabel)
                    .addComponent(deleteCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropCourseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Delete Customer", jPanel13);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        displayProductsButton.setText("Display");
        displayProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayProductsButtonActionPerformed(evt);
            }
        });

        displayProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(displayProductsTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(displayProductsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayProductsButton)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Display Products", jPanel7);

        addProductLabel.setText("Select Product");

        addProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addCustomerProductButton.setText("Submit");
        addCustomerProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerProductButtonActionPerformed(evt);
            }
        });

        addCustomerProductStatusLabel.setText("                                                           ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCustomerProductStatusLabel)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(addProductLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCustomerProductButton)
                            .addComponent(addProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCustomerProductButton)
                .addGap(29, 29, 29)
                .addComponent(addCustomerProductStatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add Product", jPanel8);

        displayCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Number of Items", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayCartTable);

        displayScheduleButton.setText("Display");
        displayScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayScheduleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(displayScheduleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayScheduleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Display Cart", jPanel9);

        deleteItemLabel.setText("Select Item:");

        deleteItemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        deleteItemButton.setText("Delete Item");
        deleteItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteItemLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteItemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(deleteItemButton)))
                .addContainerGap(683, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteItemLabel)
                    .addComponent(deleteItemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteItemButton)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Delete Item", jPanel10);

        currentCustomerLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        currentCustomerLabel.setText("Current Customer:");

        currentCustomerTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        currentCustomerTextField.setText("           ");

        currentCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currentCustomerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentCustomerComboBoxActionPerformed(evt);
            }
        });

        changeCustomerButton.setText("Change Customer");
        changeCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentCustomerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentCustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currentCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeCustomerButton)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentCustomerLabel)
                    .addComponent(currentCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeCustomerButton)
                    .addComponent(currentCustomerTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3))
        );

        jTabbedPane1.addTab("Customer", jPanel2);

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutButton)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton)
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        // display about information.
        JOptionPane.showMessageDialog(null, "Author: " + author + " Project: " + project);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void addCustomerProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerProductButtonActionPerformed
        // TODO add your handling code here:
        String semester = currentSemesterComboBox.getSelectedItem().toString();
        String courseCode = addProductComboBox.getSelectedItem().toString();
        String studentName = currentCustomerTextField.getText();
        String[] names = studentName.split(" ", 3);
        String studentID = names[2];
        studentName = names[0] + " " + names[1];

        String status = "";
        if (ScheduleQueries.getScheduledStudentCount(semester,courseCode) >= CourseQueries.getCourseSeats(semester, courseCode)) {
            status = "W";
        } else {
            status = "S";
        }
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        ScheduleQueries.addScheduleEntry(new ScheduleEntry(semester, studentID, courseCode, status, currentTimestamp));

        if (status == "W") {    
            addCustomerProductStatusLabel.setText(studentName + " has been waitlisted for the class.");    
        } else {
            addCustomerProductStatusLabel.setText(studentName + " has been scheduled for the class.");
        }
        
        rebuildComboBoxes();
    }//GEN-LAST:event_addCustomerProductButtonActionPerformed

    private void displayProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayProductsButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<CourseEntry> courses = CourseQueries.getAllCourses(currentSemesterComboBox.getSelectedItem().toString());
        DefaultTableModel displayCoursesTabelModel = (DefaultTableModel) displayProductsTable.getModel();
        Object[] rowData = new Object[3];
        displayCoursesTabelModel.setNumRows(0);
        for (CourseEntry ce : courses) {
            rowData[0] = ce.getCourseCode();
            rowData[1] = ce.getDescription();
            rowData[2] = ce.getSeats();
            displayCoursesTabelModel.addRow(rowData);
        }
    }//GEN-LAST:event_displayProductsButtonActionPerformed

    private void displayScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayScheduleButtonActionPerformed
        String studentID = currentCustomerTextField.getText().split(" ", 3)[2];
        String semester = currentSemesterLabel.getText();
        ArrayList<ScheduleEntry> schedule = ScheduleQueries.getScheduleByStudent(semester, studentID);
        DefaultTableModel displayCoursesTabelModel = (DefaultTableModel) displayCartTable.getModel();
        Object[] rowData = new Object[2];
        displayCoursesTabelModel.setNumRows(0);
        for (ScheduleEntry se : schedule) {
            rowData[0] = se.getCourseCode();
            if (se.getStatus().equals("W")) {
                rowData[1] = "Waitlisted";
            } else {
                rowData[1] = "Scheduled";
            }
            displayCoursesTabelModel.addRow(rowData);
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_displayScheduleButtonActionPerformed

    private void deleteItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemButtonActionPerformed
        // TODO add your handling code here:
        dropCourseTextArea.setText("");
        String semester = currentSemesterLabel.getText();
        String studentID = currentCustomerTextField.getText().split(" ", 3)[2];
        String courseCode = deleteItemComboBox.getSelectedItem().toString();
        ArrayList<ScheduleEntry> w = ScheduleQueries.getWaitlistedStudentsByCourse(semester, courseCode);
        
        ScheduleQueries.dropStudentScheduleByCourse(semester, studentID, courseCode);
        ArrayList<ScheduleEntry> waitlisted = ScheduleQueries.getWaitlistedStudentsByCourse(semester, courseCode);
        if (w.size() != waitlisted.size()) {
            // person was on waitlist
            dropCourseTextArea.append(currentCustomerTextField.getText() + " has been dropped from the waitlist for " + courseCode + "\n");
        } else {
            // schedule new person
            dropCourseTextArea.append(currentCustomerTextField.getText() + " has been dropped from " + courseCode + "\n");
            if (waitlisted.size() > 0) {
                ScheduleQueries.updateScheduleEntry(semester,waitlisted.get(0));
                StudentEntry waitlistedStudent = StudentQueries.getStudent(waitlisted.get(0).getStudentID());
                String name = waitlistedStudent.getLastName() + ", " + waitlistedStudent.getFirstName() + " " + waitlistedStudent.getStudentID();
                dropCourseTextArea.append(name + " has been scheduled into " + courseCode);
            }
        }

        
        
    }//GEN-LAST:event_deleteItemButtonActionPerformed

    private void currentCustomerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentCustomerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentCustomerComboBoxActionPerformed

    private void changeCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCustomerButtonActionPerformed
        // TODO add your handling code here:
        currentCustomerTextField.setText(currentCustomerComboBox.getSelectedItem().toString());
        rebuildComboBoxes();
        
    }//GEN-LAST:event_changeCustomerButtonActionPerformed

    private void dropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropCourseButtonActionPerformed
        // TODO add your handling code here:
        deleteCustomerTextArea.setText("");
        String courseCode = deleteCustomerComboBox.getSelectedItem().toString();
        String semester = currentSemesterLabel.getText();
        CourseQueries.dropCourse(semester, courseCode);
        deleteCustomerTextArea.append("Scheduled students dropped from the course: \n");
        ArrayList<ScheduleEntry> students = ScheduleQueries.getScheduledStudentsByCourse(semester, courseCode);
        ArrayList<ScheduleEntry> waitlist = ScheduleQueries.getWaitlistedStudentsByCourse(semester, courseCode);
        for (ScheduleEntry s : students) {
            String studentID = s.getStudentID();
            StudentEntry student = StudentQueries.getStudent(studentID);
            String name = student.getLastName() + ", " + student.getFirstName() + " " + student.getStudentID();
            deleteCustomerTextArea.append(name + "\n");
            ScheduleQueries.dropStudentScheduleByCourse(semester, studentID, courseCode);
        }
        deleteCustomerTextArea.append("\nWaitlisted students dropped from the course: \n");

        for (ScheduleEntry s : waitlist) {
            String studentID = s.getStudentID();
            StudentEntry student = StudentQueries.getStudent(studentID);
            String name = student.getLastName() + ", " + student.getFirstName() + " " + student.getStudentID();
            deleteCustomerTextArea.append(name + "\n");
            ScheduleQueries.dropStudentScheduleByCourse(semester, studentID, courseCode);
        }

        rebuildComboBoxes();
    }//GEN-LAST:event_dropCourseButtonActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
        String studentID = addCustomerIDTextField.getText();
        String firstName = addFirstNameTextField.getText();
        String lastName = addLastNameTextField.getText();
        StudentQueries.addStudent(new StudentEntry(studentID, firstName, lastName));
        addCustomerStatusLabel.setText(lastName+", "+firstName+" has been added.");
        rebuildComboBoxes();
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void addCustomerIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerIDTextFieldActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        // TODO add your handling code here:
        String courseCode = addProductNameTextField.getText();
        String courseDescription = addProductIDTextField.getText();
        int seats = (int) addCourseSeatsSpinner.getValue();
        CourseQueries.addCourse(currentSemesterLabel.getText(), courseCode, courseDescription, seats);
        addProductStatusLabel.setText(courseCode + " has been added.");
        rebuildComboBoxes();
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        // TODO add your handling code here:
        deleteProductTextArea.setText("");
        String studentID = deleteProductComboBox.getSelectedItem().toString().split(" ", 3)[2];
        StudentEntry student = StudentQueries.getStudent(studentID);
        String name = student.getLastName() + ", " + student.getFirstName() + " " + student.getStudentID();
        StudentQueries.dropStudent(studentID);
        deleteProductTextArea.append(name + " has been dropped from the list of students. \n\n");
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        for (String s : semesters) {
            ArrayList <ScheduleEntry> schedule = ScheduleQueries.getScheduleByStudent(s, studentID);
            if (schedule.size() > 0) {
                deleteProductTextArea.append("For Semester " + s + "\n");
                for (ScheduleEntry se : schedule) {
                    if (se.getStatus().equals("W")) {
                        ScheduleQueries.dropStudentScheduleByCourse(s, studentID, se.getCourseCode());
                        deleteProductTextArea.append(name + " has been dropped from the waitlist for " + se.getCourseCode() + "\n");
                    } else {
                        ScheduleQueries.dropStudentScheduleByCourse(s, studentID, se.getCourseCode());
                        deleteProductTextArea.append(name + " has been dropped from " + se.getCourseCode() + "\n");
                        ArrayList <ScheduleEntry> waitlist = ScheduleQueries.getWaitlistedStudentsByCourse(s, se.getCourseCode());
                        if (waitlist.size() > 0) {
                            ScheduleQueries.updateScheduleEntry(s, waitlist.get(0));
                            StudentEntry waitlistedStudent = StudentQueries.getStudent(waitlist.get(0).getStudentID());
                            String waitlistedName = waitlistedStudent.getLastName() + ", " + waitlistedStudent.getFirstName() + " " + waitlistedStudent.getStudentID();
                            deleteProductTextArea.append(waitlistedName + " has been scheduled into " + se.getCourseCode() + "\n");
                        }
                    }
                }
                deleteProductTextArea.append("\n");
            }

        }
        rebuildComboBoxes();
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    
    private void checkData() {
        try {
            FileReader reader = new FileReader("xzq789yy.txt");
            BufferedReader breader = new BufferedReader(reader);

            String encodedAuthor = breader.readLine();
            String encodedProject = breader.readLine();
            byte[] decodedAuthor = Base64.getDecoder().decode(encodedAuthor);
            author = new String(decodedAuthor);
            byte[] decodedProject = Base64.getDecoder().decode(encodedProject);
            project = new String(decodedProject);
            reader.close();

        } catch (FileNotFoundException e) {
            //get user info and create file
            author = JOptionPane.showInputDialog("Enter your first and last name.");
            project = "Course Scheduler Spring 2023";

            //write data to the data file.
            try {
                FileWriter writer = new FileWriter("xzq789yy.txt", true);
                BufferedWriter bufferedWriter = new BufferedWriter(writer);

                // encode the output data.
                String encodedAuthor = Base64.getEncoder().encodeToString(author.getBytes());

                bufferedWriter.write(encodedAuthor);
                bufferedWriter.newLine();

                String encodedProject = Base64.getEncoder().encodeToString(project.getBytes());
                bufferedWriter.write(encodedProject);

                bufferedWriter.close();
            } catch (IOException ioe) {
                ioe.printStackTrace();
                System.exit(1);
            }

        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JLabel addCourseLabel;
    private javax.swing.JLabel addCourseSeatsLabel;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextField addCustomerIDTextField;
    private javax.swing.JButton addCustomerProductButton;
    private javax.swing.JLabel addCustomerProductStatusLabel;
    private javax.swing.JLabel addCustomerStatusLabel;
    private javax.swing.JLabel addFirstNameLabel;
    private javax.swing.JTextField addFirstNameTextField;
    private javax.swing.JLabel addLastNameLabel;
    private javax.swing.JTextField addLastNameTextField;
    private javax.swing.JTextField addPriceTextField;
    private javax.swing.JButton addProductButton;
    private javax.swing.JComboBox<String> addProductComboBox;
    private javax.swing.JLabel addProductIDLabel;
    private javax.swing.JTextField addProductIDTextField;
    private javax.swing.JLabel addProductLabel;
    private javax.swing.JLabel addProductNameLabel;
    private javax.swing.JTextField addProductNameTextField;
    private javax.swing.JLabel addProductStatusLabel;
    private javax.swing.JLabel addStudentStudentIDLabel;
    private javax.swing.JLabel addTypeLabel;
    private javax.swing.JTextField addTypeTextField;
    private javax.swing.JLabel addWeightLabel;
    private javax.swing.JTextField addWeightTextField;
    private javax.swing.JButton changeCustomerButton;
    private javax.swing.JComboBox<String> currentCustomerComboBox;
    private javax.swing.JLabel currentCustomerLabel;
    private javax.swing.JLabel currentCustomerTextField;
    private javax.swing.JComboBox<String> deleteCustomerComboBox;
    private javax.swing.JLabel deleteCustomerLabel;
    private javax.swing.JTextArea deleteCustomerTextArea;
    private javax.swing.JButton deleteItemButton;
    private javax.swing.JComboBox<String> deleteItemComboBox;
    private javax.swing.JLabel deleteItemLabel;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JComboBox<String> deleteProductComboBox;
    private javax.swing.JLabel deleteProductLabel;
    private javax.swing.JTextArea deleteProductTextArea;
    private javax.swing.JTable displayCartTable;
    private javax.swing.JButton displayProductsButton;
    private javax.swing.JTable displayProductsTable;
    private javax.swing.JButton displayScheduleButton;
    private javax.swing.JButton dropCourseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
    
}
